<?php

namespace Database\Seeders;

use App\Models\Surah;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        Surah::create(['name'=>'الفاتحة','active'=>true]);
        Surah::create(['name'=>'البقرة','active'=>true]);
        Surah::create(['name'=>'ال عمران','active'=>true]);
        Surah::create(['name'=>'النساء','active'=>true]);
        Surah::create(['name'=>'المائدة','active'=>true]);
        Surah::create(['name'=>'الأنعام','active'=>true]);
        Surah::create(['name'=>'الأعراف','active'=>true]);
        Surah::create(['name'=>'الأنفال','active'=>true]);
        Surah::create(['name'=>'التوبة','active'=>true]);
        Surah::create(['name'=>'يونس','active'=>true]);
        Surah::create(['name'=>'هود','active'=>true]);
        Surah::create(['name'=>'يوسف','active'=>true]);
        Surah::create(['name'=>'الرعد','active'=>true]);
        Surah::create(['name'=>'إبراهيم','active'=>true]);
        Surah::create(['name'=>'الحجر','active'=>true]);
        Surah::create(['name'=>'النحل','active'=>true]);
        Surah::create(['name'=>'الإسراء','active'=>true]);
        Surah::create(['name'=>'الكهف','active'=>true]);
        Surah::create(['name'=>'مريم','active'=>true]);
        Surah::create(['name'=>'طه','active'=>true]);
        Surah::create(['name'=>'الأنبياء','active'=>true]);
        Surah::create(['name'=>'الحج','active'=>true]);
        Surah::create(['name'=>'المؤمنون','active'=>true]);
        Surah::create(['name'=>'النور','active'=>true]);
        Surah::create(['name'=>'الفرقان','active'=>true]);
        Surah::create(['name'=>'النمل','active'=>true]);
        Surah::create(['name'=>'القصص','active'=>true]);
        Surah::create(['name'=>'العنكبوت','active'=>true]);
        Surah::create(['name'=>'الروم','active'=>true]);
        Surah::create(['name'=>'لقمان','active'=>true]);
        Surah::create(['name'=>'السجدة','active'=>true]);
        Surah::create(['name'=>'الأحزاب','active'=>true]);
        Surah::create(['name'=>'سبأ','active'=>true]);
        Surah::create(['name'=>'فاطر','active'=>true]);
        Surah::create(['name'=>'يس','active'=>true]);
        Surah::create(['name'=>'الصافات','active'=>true]);
        Surah::create(['name'=>'ص','active'=>true]);
        Surah::create(['name'=>'الزمر','active'=>true]);
        Surah::create(['name'=>'غافر','active'=>true]);
        Surah::create(['name'=>'فصلت','active'=>true]);
        Surah::create(['name'=>'الشورى','active'=>true]);
        Surah::create(['name'=>'الزخرف','active'=>true]);
        Surah::create(['name'=>'الدخان','active'=>true]);
        Surah::create(['name'=>'الجاثية','active'=>true]);
        Surah::create(['name'=>'الأحقاف','active'=>true]);
        Surah::create(['name'=>'محمد','active'=>true]);
        Surah::create(['name'=>'الفتح','active'=>true]);
        Surah::create(['name'=>'الحجرات','active'=>true]);
        Surah::create(['name'=>'ق','active'=>true]);
        Surah::create(['name'=>'الذاريات','active'=>true]);
        Surah::create(['name'=>'الطور','active'=>true]);
        Surah::create(['name'=>'النجم','active'=>true]);
        Surah::create(['name'=>'القمر','active'=>true]);
        Surah::create(['name'=>'الرحمن','active'=>true]);
        Surah::create(['name'=>'الواقعة','active'=>true]);
        Surah::create(['name'=>'الحديد','active'=>true]);
        Surah::create(['name'=>'المجادلة','active'=>true]);
        Surah::create(['name'=>'الحشر','active'=>true]);
        Surah::create(['name'=>'الممتحنة','active'=>true]);
        Surah::create(['name'=>'الصف','active'=>true]);
        Surah::create(['name'=>'الصف','active'=>true]);
        Surah::create(['name'=>'الجمعة','active'=>true]);
        Surah::create(['name'=>'المنافقون','active'=>true]);
        Surah::create(['name'=>'التغابن','active'=>true]);
        Surah::create(['name'=>'الطلاق','active'=>true]);
        Surah::create(['name'=>'التحريم','active'=>true]);
        Surah::create(['name'=>'الملك','active'=>true]);
        Surah::create(['name'=>'القلم','active'=>true]);
        Surah::create(['name'=>'الحاقة','active'=>true]);
        Surah::create(['name'=>'المعارج','active'=>true]);
        Surah::create(['name'=>'نوح','active'=>true]);
        Surah::create(['name'=>'الجن','active'=>true]);
        Surah::create(['name'=>'المزمل','active'=>true]);
        Surah::create(['name'=>'المدثر','active'=>true]);
        Surah::create(['name'=>'القيامة','active'=>true]);
        Surah::create(['name'=>'الإنسان','active'=>true]);
        Surah::create(['name'=>'المرسلات','active'=>true]);
        Surah::create(['name'=>'النبأ','active'=>true]);
        Surah::create(['name'=>'النازعات','active'=>true]);
        Surah::create(['name'=>'عبس','active'=>true]);
        Surah::create(['name'=>'التكوير','active'=>true]);
        Surah::create(['name'=>'الإنفطار','active'=>true]);
        Surah::create(['name'=>'المطففين','active'=>true]);
        Surah::create(['name'=>'الإنشقاق','active'=>true]);
        Surah::create(['name'=>'البروج','active'=>true]);
        Surah::create(['name'=>'الطارق','active'=>true]);
        Surah::create(['name'=>'الأعلى','active'=>true]);
        Surah::create(['name'=>'الغاشية','active'=>true]);
        Surah::create(['name'=>'الفجر','active'=>true]);
        Surah::create(['name'=>'البلد','active'=>true]);
        Surah::create(['name'=>'الشمس','active'=>true]);
        Surah::create(['name'=>'الليل','active'=>true]);
        Surah::create(['name'=>'الضحى','active'=>true]);
        Surah::create(['name'=>'الشرح','active'=>true]);
        Surah::create(['name'=>'التين','active'=>true]);
        Surah::create(['name'=>'العلق','active'=>true]);
        Surah::create(['name'=>'القدر','active'=>true]);
        Surah::create(['name'=>'البينة','active'=>true]);
        Surah::create(['name'=>'الزلزلة','active'=>true]);
        Surah::create(['name'=>'العاديات','active'=>true]);
        Surah::create(['name'=>'القارعة','active'=>true]);
        Surah::create(['name'=>'التكاثر','active'=>true]);
        Surah::create(['name'=>'العصر','active'=>true]);
        Surah::create(['name'=>'الهمزة','active'=>true]);
        Surah::create(['name'=>'الفيل','active'=>true]);
        Surah::create(['name'=>'قريش','active'=>true]);
        Surah::create(['name'=>'الماعون','active'=>true]);
        Surah::create(['name'=>'الكزثر','active'=>true]);
        Surah::create(['name'=>'الكافرون','active'=>true]);
        Surah::create(['name'=>'النصر','active'=>true]);
        Surah::create(['name'=>'المسد','active'=>true]);
        Surah::create(['name'=>'الإخلاص','active'=>true]);
        Surah::create(['name'=>'الفلق','active'=>true]);
        Surah::create(['name'=>'الناس','active'=>true]);
    }
}
